### ISSUE TITLE
Launch problems

### ISSUE THREAD

**Issue by fixxOrz** [shumatech/gorom#1]
I really like what you're doing here, and there's such a lack of good Linux rom tools that I'd like to help out. I haven't reported an issue on github before, so I hope I'm doing it right and that it's helpful.

Per the install instructions ("Download a release and copy the files to somewhere on your path."), I downloaded 'gorom-0.1.1.tar.gz' to `$HOME/bin` and extracted the file there creating the directory `$HOME/bin/gorom-0.1.1`. Per the build instructions, I cd'd to `./gorom-0.1.1`, ran `make test` and got the following messages:

	fatal: not a git repository (or any parent up to mount point /)
	Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
	fatal: not a git repository (or any parent up to mount point /)
	Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

Otherwise the tests looked OK, so I ran `make` and got the same messages. I'm not sure if these messages are a problem, but I mention them in case they are related to what is a problem:

After running `make`, the gorom and goromui binaries are both in `/gorom-0.1.1/bin`, but when I try to run `gorom --help` I get the error message: "gorom: command not found." I have to run `$HOME/bin/gorom-0.1.1/bin/gorom --help` to see the help screen.

`$HOME/bin` is in my `$PATH`, so why won't `gorom` launch without having to specify the full directory path?

I have the same problem running `goromui` but even specifying the full directory path doesn't help, so it doesn't launch at all.

If I try to run `goromui` from the command line I get the error message: "goromui: command not found". If I run `$HOME/bin/gorom-0.1.1/bin/goromui` I get the error message:

	[sciter-x-api.c] Unable to load library: libsciter-gtk.so: cannot open shared object file: No such file or directory
	[sciter-x-api.c] Unable to load library: $HOME/bin/gorom-0.1.1/bin/libsciter-gtk.so: cannot open shared object file: No such file or directory

Why won't `goromui` launch even when specifying the full directory path?

**Comment by shumatech** [comment]
The build process is trying to get the source repository version so it can build it into the 
executable. Since you installed with a tar ball and not with git, that part of the build will spit 
out an error but it is harmless.

The PATH will not look in subdirectories so you'll need to copy the gorom, goromui, and 
libsciter-gtk.so into your $HOME/bin directory.

goromui needs the libsciter-gtk.so to run so put that in the same directory as gorom ($HOME/bin in 
your case).

If you want a system-wide install that does not depend on a custom PATH, then copy gorom and goromui 
to /usr/bin (or /usr/local/bin) and libsciter-gtk.so to /usr/lib (or /usr/local/lib).

-Scott

**Comment by fixxOrz** [comment]
Got it! Thank you my friend! Keep up the great work.
